load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_target", "rn_android_library", "rn_xplat_cxx_library")

rn_xplat_cxx_library(
    name = "jni-interface",
    srcs = [],
    header_namespace = "hermes/reactexecutor",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
)

rn_xplat_cxx_library(
    name = "jni",
    srcs = ["OnLoad.cpp"],
    headers = [],
    header_namespace = "",
    compiler_flags = ["-fexceptions"],
    soname = "libhermes-executor.$(ext)",
    visibility = [
        react_native_target("java/com/facebook/hermes/reactexecutor:reactexecutor"),
    ],
)
